version: '3.7'
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: bdpocpsl
      MYSQL_USER: psl
      MYSQL_PASSWORD: psl
    container_name: bdpocpsl

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "80:3000"
    links:
      - "mysql:mysql"
    container_name: pocapp
    environment:
      DB_HOST: mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: psl
      MYSQL_PASSWORD: psl
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "8080:80"
    links:
      - "mysql:mysql"

    container_name: myadmin

